spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex?characterEncoding=UTF-8&serverTimezone=UTC
    username: bootex
    password: bootex
  security:
    debug: true

  jpa:
    hibernate:
      ddl-auto: update
      # (create, update, create-drop, validate)
      # update : 변경이 필요할경우에 alter로 변경, 테이블이 없는 경우에는 create되도록 설정
    properties:
      hibernate:
        format_sql: true
        # JPA 구현체인 hibernate가 동작하면서 발생하는 SQL을 포맷팅해서 출력
        show_sql: true
        # JPA 처리 시에 발생하는 SQL을 보여줄것인지를 결정

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG